apiVersion: v1
kind: Service
metadata:
  name:  elasticsearch-master-svc
  namespace: observability
  labels:
      app: elasticsearch-master
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: httpelastic
  selector:
      app: elasticsearch-master     

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: production-elasticsearch
    meta.helm.sh/release-namespace: observability
    nginx.ingress.kubernetes.io/rewrite-target: ""
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app.kubernetes.io/instance: production-elasticsearch
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/version: 1.16.0
  name: production-elasticsearch
  namespace: observability
spec:
  rules:
  - host: elasticsearch.bc{Team Color}.davincipay.com
    http:
      paths:
      - backend:
          service:
            name: elasticsearch-master-svc
            port:
              number: 9200
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - elasticsearch.bc{Team Color}.davincipay.com
    secretName: tls-production-elasticsearch

