apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: observability
  labels:
     app.kubernetes.io/name: grafana
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: httpgrafana
  selector:
     app.kubernetes.io/name: grafana

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: production-grafana
    meta.helm.sh/release-namespace: observability
    nginx.ingress.kubernetes.io/rewrite-target: ""
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app.kubernetes.io/instance: production-grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 1.16.0
  name: production-grafana
  namespace: observability
spec:
  rules:
  - host: grafana.bcblue.davincipay.com
    http:
      paths:
      - backend:
          service:
            name: grafana-svc
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - grafana.bcblue.davincipay.com
    secretName: tls-production-grafana

