kind: Deployment
apiVersion: apps/v1
metadata:
  name: zipkin
  namespace: production
  labels:
    service: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      service: zipkin
  template:
    metadata:
      labels:
        service: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin-slim
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9411
              protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: zipkin
  namespace: production
  labels:
    service: zipkin
spec:
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
      name: zipkin
  selector:
    service: zipkin

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: production-zipkin
    meta.helm.sh/release-namespace: production
    nginx.ingress.kubernetes.io/rewrite-target: ""
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app.kubernetes.io/instance: production-zipkin
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/version: 1.16.0
  name: production-zipkin
  namespace: production
spec:
  rules:
  - host: zipkin.bc{Team Color}.davincipay.com
    http:
      paths:
      - backend:
          service:
            name: zipkin
            port:
              number: 9411
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - zipkin.bc{Team Color}.davincipay.com
    secretName: tls-production-zipkin

